INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Skin & VD', 'skin-cell.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Hematology', 'hematology.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Physical Medicine', 'physical-medicine.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Rheumatology', 'rheumatology.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Gynae & Obs', 'gynecology.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'ENT', 'ent.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`, `icon_url`) VALUES ( 'Burn & Plastic Surgery', 'burn-and-plastic-surgery.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Orthopedics', 'orthopedics.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`, `icon_url`) VALUES ( 'Gastroenterology', 'stomach.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Allergy & Immunology', 'allergies.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Oncology', 'cancer-cell.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Pediatric Surgery', 'pediatrics-surgery.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Chest Disease', 'chest.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Psychiatry', 'human-brain.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Surgery', 'surgery.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Ophthalmology (Eye)', 'eye.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Diabetology & Endocrinology', 'endocrine.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Medicine', 'medicine.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Nephrology','nephrology.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Urology', 'urology.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Hepatology', 'liver.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Dentistry', 'dental-care.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Pediatrics', 'pediatrics.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Physiotherapy', 'injury.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Food & Nutrition', 'nutrition.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Cardiology', 'cardiology.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Neuro Medicine', 'brain.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'General Practitioner', 'stethoscope.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`) VALUES ( 'Breast Diseases', 'breasts.png');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`, `icon_url`) VALUES ( 'Neuro Surgery', 'neurosurgery.png');
