INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Skin & VD', '0','skin-cell.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Hematology', '0','hematology.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Physical Medicine', '0','physical-medicine.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Rheumatology', '0','rheumatology.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Gynae & Obs', '0','gynecology.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'ENT', '0','ent.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Burn & Plastic Surgery', '0','burn-and-plastic-surgery.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Orthopedics', '0','orthopedics.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Gastroenterology', '0','stomach.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Allergy & Immunology', '0','allergies.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Oncology', '0','cancer-cell.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Pediatric Surgery', '0','pediatrics-surgery.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Chest Disease', '0','chest.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Psychiatry', '0','human-brain.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Surgery', '0','surgery.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Ophthalmology (Eye)', '0','eye.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Diabetology & Endocrinology', '0','endocrine.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Medicine', '0','medicine.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Nephrology', '0','nephrology.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Urology', '0','urology.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Hepatology', '0','liver.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Dentistry', '0','dental-care.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Pediatrics', '0','pediatrics.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Physiotherapy', '0','injury.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Food & Nutrition', '0','nutrition.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Cardiology', '0','cardiology.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Neuro Medicine', '0','brain.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'General Practitioner', '0','stethoscope.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Breast Diseases', '0','breasts.png');
INSERT INTO `billing_system`.`specialist` (`med_spec_name`, `no_of_doctor`, `icon_url`) VALUES ( 'Neuro Surgery', '0','neurosurgery.png');
