INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Skin & VD', 'skin-cell.png','branch of medicine which deals with all types of skin, hair & nail problems');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Hematology', 'hematology.png','branch of medicine involving study and treatment of the blood.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Physical Medicine', 'physical-medicine.png','a branch of medicine that aims to enhance and restore functional ability');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Rheumatology', 'rheumatology.png','branch of medicine devoted to the diagnosis and management of disorders');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Gynae & Obs', 'gynecology.png','encompasses the two subspecialties of obstetrics and gynecology');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'ENT', 'ent.png', 'medical conditions of the ear, nose, throat, and neck');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`, `icon_url`, `description`) VALUES ( 'Burn & Plastic Surgery', 'burn-and-plastic-surgery.png','Medical specialty for repairing burns and trauma-related injuries.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Orthopedics', 'orthopedics.png','Treatment of musculoskeletal conditions.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`, `icon_url`, `description`) VALUES ( 'Gastroenterology', 'stomach.png','Digestive system medical specialty.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Allergy & Immunology', 'allergies.png','Medical specialty dealing with allergies and the immune system.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Oncology', 'cancer-cell.png','Cancer care and treatment.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Pediatric Surgery', 'pediatrics-surgery.png','Surgery for children''s medical conditions.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Chest Disease', 'chest.png','Medical field specializing in chest-related illnesses.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Psychiatry', 'human-brain.png','Medical field for diagnosing and treating mental health disorders.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Surgery', 'surgery.png','Medical procedures for treating injuries and conditions.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Ophthalmology (Eye)', 'eye.png','Medical field focused on eye health and vision care.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Diabetology & Endocrinology', 'endocrine.png','Study and treatment of diabetes and hormonal disorders.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Medicine', 'medicine.png','Medical science and treatment.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Nephrology','nephrology.png','Kidney disease and treatment specialty.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Urology', 'urology.png','Medical field specializing in urinary tract and male reproductive system health.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Hepatology', 'liver.png','Study and treatment of liver diseases.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Dentistry', 'dental-care.png','Oral health care profession.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Pediatrics', 'pediatrics.png','Medical care for children.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Physiotherapy', 'injury.png','rehabilitation through movement and exercise.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Food & Nutrition', 'nutrition.png','Diet and nourishment: Eating for health and well-being.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Cardiology', 'cardiology.png','Heart medicine.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Neuro Medicine', 'brain.png','Medical field specializing in neurological disorders.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'General Practitioner', 'stethoscope.png','Primary care doctor for general health concerns.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`,  `icon_url`, `description`) VALUES ( 'Breast Diseases', 'breasts.png','Medical conditions affecting the breasts.');
INSERT INTO `billing_system`.`speciality` (`med_spec_name`, `icon_url`, `description`) VALUES ( 'Neuro Surgery', 'neurosurgery.png','Surgery for neurological conditions.');
